### PR TITLE
fix star power tilt

### PR DESCRIPTION
**Pull request by Lana-chan**
current calc measures the wrong axis and is just generally narsty

### CODE REVIEW

**Comment by TheNathannator** [comment]
Thanks for looking into this! I'll have to get another release out sometime soon, been putting that off for a while lol

**Comment by Lana-chan** [comment]
boy do i feel silly. i swapped lines https://github.com/TheNathannator/WiitarThing/pull/19/files#diff-9a77eea1abe57ac4932dc0b07b12314ed06dcc28aefa9a7e21cd977326e34e49R512-R513 and so the smoothing doesn't actually do anything. would you like me to submit another PR or do you just wanna commit that fix yourself?

**Comment by Lana-chan** [comment]
i say this after playing like several hours of YARG with my fork thinking it was working, lol

**Comment by TheNathannator** [comment]
ah rip, I can take care of that in the morning. Gonna return to working on this dreaded program once more and make it less dreaded lol

**Comment by TheNathannator** [comment]
Alright, got that fixed!

**Pull request merged**
